#!/usr/bin/env node
/**
 * Ports a Claude Design `.dc.html` page into the Next.js app without retyping it.
 *
 *   node scripts/port-dc.mjs "mockup/v3/Everstock v3.dc.html" "mockup/v3/support.js" components/v3/generated
 *
 * The design runs on the dc-runtime (support.js): a template compiled at runtime into
 * React elements, driven by a logic class. This script does the compile step ahead of
 * time with the runtime's own code (sliced out of support.js, not re-implemented):
 *
 *   template.json  the template as a node tree, attribute keys already resolved the way
 *                  collectProps() resolves them; values keep their {{ }} holes
 *   pseudo.css     style-hover / style-focus / style-active rules, same class names and
 *                  !important treatment as createPseudoSheet()
 *   helmet.css     the <style> block from the <helmet>
 *   logic.js       the logic <script>, byte-for-byte, wrapped exactly like evalDcLogic()
 *   dcrt.js        the runtime's expression + attribute helpers (src/expr.ts, src/encode.ts)
 *   props.json     the declared props' defaults
 */
import fs from "node:fs";
import path from "node:path";
import { parseFragment } from "parse5";

const [, , srcPath, runtimePath, outDir] = process.argv;
if (!srcPath || !runtimePath || !outDir) {
  console.error("usage: port-dc.mjs <page.dc.html> <support.js> <outDir>");
  process.exit(1);
}
const html = fs.readFileSync(srcPath, "utf8");
const support = fs.readFileSync(runtimePath, "utf8");
fs.mkdirSync(outDir, { recursive: true });

/* ---------- runtime sections, sliced verbatim ---------- */
function section(name) {
  const start = support.indexOf("  // src/" + name + ".ts");
  if (start < 0) throw new Error("support.js: no section " + name);
  const next = support.indexOf("  // src/", start + 10);
  return support.slice(start, next);
}
const exprSrc = section("expr");
const encodeSrc = section("encode");
const pseudoSrc = section("pseudo");

// build-time copies of the runtime helpers
const rt = new Function(
  exprSrc + encodeSrc + pseudoSrc +
    "\nreturn { resolve, encodeCase, kebabToCamel, CAMEL_ATTR, RAW_UNWRAP, EVENT_MAP, importantify };"
)();

// the same helpers for the browser, as an ES module
fs.writeFileSync(
  path.join(outDir, "dcrt.js"),
  "// GENERATED by scripts/port-dc.mjs from the dc-runtime (support.js) — do not edit.\n" +
    "/* eslint-disable */\n" +
    exprSrc + encodeSrc +
    "\nexport { resolve, compileAttr, cssToObj, kebabToCamel };\n"
);

/* ---------- split the document ---------- */
const dcOpen = html.indexOf("<x-dc>");
const dcClose = html.lastIndexOf("</x-dc>");
let inner = html.slice(dcOpen + "<x-dc>".length, dcClose);

const helmetMatch = inner.match(/<helmet>([\s\S]*?)<\/helmet>/i);
if (!helmetMatch) throw new Error("no <helmet>");
const helmet = helmetMatch[1];
inner = inner.replace(helmetMatch[0], "");

const styles = [...helmet.matchAll(/<style>([\s\S]*?)<\/style>/gi)].map((m) => m[1]);
fs.writeFileSync(
  path.join(outDir, "helmet.css"),
  "/* GENERATED by scripts/port-dc.mjs: the page's <helmet> <style>, verbatim. */\n" + styles.join("\n")
);

const scriptMatch = html.match(/<script type="text\/x-dc" data-dc-script data-props="([^"]*)">([\s\S]*)<\/script>\s*<\/body>/);
if (!scriptMatch) throw new Error("no logic <script>");
const decode = (s) => s.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
const propsMeta = JSON.parse(decode(scriptMatch[1]));
const defaults = Object.fromEntries(Object.entries(propsMeta).filter(([, m]) => m.default !== undefined).map(([k, m]) => [k, m.default]));
fs.writeFileSync(path.join(outDir, "props.json"), JSON.stringify(defaults, null, 2) + "\n");

fs.writeFileSync(
  path.join(outDir, "logic.js"),
  "// GENERATED by scripts/port-dc.mjs: the design's logic <script>, byte-for-byte, wrapped\n" +
    "// the way the dc-runtime's evalDcLogic() wraps it. Do not edit; re-run the port.\n" +
    "/* eslint-disable */\n" +
    "export default function defineLogic(DCLogic, StreamableLogic, React) {\n" +
    scriptMatch[2] +
    '\n;return (typeof Component!=="undefined"&&Component)||undefined;\n}\n'
);

/* ---------- template -> node tree (compileTemplate / walk / collectProps) ---------- */
const frag = parseFragment(rt.encodeCase(inner));
const pseudoCache = new Map();
const pseudoRules = [];
function pseudoClass(pseudo, css) {
  const k = pseudo + "|" + css;
  if (pseudoCache.has(k)) return pseudoCache.get(k);
  const cls = "scp" + pseudoRules.length.toString(36);
  const isEl = pseudo === "before" || pseudo === "after";
  const sel = isEl ? "." + cls + "::" + pseudo : "." + cls + ":" + pseudo;
  pseudoRules.push(sel + "{" + (isEl ? css : rt.importantify(css)) + "}");
  pseudoCache.set(k, cls);
  return cls;
}

/* Asset URLs that deliberately differ from the design. The design points at the
   pre-upscale CloudFront original of the guardrail clip because Claude Design cannot
   reach the repo; the corrected/upscaled copy in public/videos is the one we ship. */
const SRC_OVERRIDES = {
  "https://d8j0ntlcm91z4.cloudfront.net/user_3FMfW2x8TD9jPPPVdRryKluSeEm/hf_20260823_052642_1d43c521-6909-47da-af26-1642ff625320.mp4#t=0.1":
    "/videos/beat3-approve.mp4#t=0.1",
};

const tags = new Set();
function walk(node) {
  if (node.nodeName === "#text") {
    const txt = node.value ?? "";
    if (!txt.includes("{{") && !txt.trim() && !txt.includes(" ")) return null;
    return { t: "text", v: txt };
  }
  if (!node.tagName) return null; // comments
  const kids = () => {
    const src = node.tagName === "template" ? node.content.childNodes : node.childNodes;
    return src.map(walk).filter(Boolean);
  };
  const attr = (n) => node.attrs.find((a) => a.name === n)?.value;
  const tag = node.tagName.toLowerCase();
  if (tag === "sc-for") return { t: "for", list: attr("list") || "", as: attr("as") || "item", kids: kids() };
  if (tag === "sc-if") return { t: "if", value: attr("value") || "", kids: kids() };
  if (tag === "x-import" || tag === "dc-import" || tag === "sc-helmet") throw new Error("unsupported: <" + tag + ">");

  const props = [];
  const classes = [];
  for (const { name, value } of node.attrs) {
    if (name === "sc-name" || name === "data-dc-tpl") continue;
    let key = name;
    if (key.startsWith(rt.CAMEL_ATTR)) key = rt.kebabToCamel(key.slice(rt.CAMEL_ATTR.length));
    if (key === "hint-size") continue;
    if (key.startsWith("style-")) {
      classes.push(pseudoClass(key.slice(6), value));
      continue;
    }
    if (key === "class") key = "className";
    else if (key === "for") key = "htmlFor";
    else if (key.startsWith("on")) key = rt.EVENT_MAP[key] || "on" + key[2].toUpperCase() + key.slice(3);
    props.push([key, key === "src" && SRC_OVERRIDES[value] ? SRC_OVERRIDES[value] : value]);
  }
  const realTag = rt.RAW_UNWRAP[tag] || tag;
  tags.add(realTag);
  const out = { t: "el", tag: realTag, props, kids: kids() };
  if (classes.length) out.cls = classes;
  return out;
}
const tree = frag.childNodes.map(walk).filter(Boolean);
fs.writeFileSync(path.join(outDir, "template.json"), JSON.stringify(tree));
fs.writeFileSync(
  path.join(outDir, "pseudo.css"),
  "/* GENERATED by scripts/port-dc.mjs: style-hover/-focus/-active from the template. */\n" + pseudoRules.join("\n") + "\n"
);

console.log(
  `template: ${tree.length} root nodes, tags: ${[...tags].sort().join(" ")}\n` +
    `pseudo rules: ${pseudoRules.length}\nlogic: ${scriptMatch[2].length} chars\nprops: ${JSON.stringify(defaults)}\n` +
    `helmet links:\n${[...helmet.matchAll(/<link[^>]*>/gi)].map((m) => "  " + m[0]).join("\n")}\n` +
    `helmet scripts:\n${[...helmet.matchAll(/<script[^>]*>/gi)].map((m) => "  " + m[0]).join("\n")}`
);
